services:
  kafka:
    build: ./kafka
    image: bitnami/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"   # internal (for containers)
      - "9094:9094"   # external (for host / macOS)
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_KRAFT_CLUSTER_ID: my-cluster-id
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094


  # producer:
  #   build: ./producer
  #   restart: on-failure
  #   depends_on:
  #     - kafka
  #   volumes:
  #     - ./input:/input

  spark:
    build: ./spark
    depends_on:
      - kafka
    volumes:
      - ./input:/input
      - ./output:/output

  # video-consumer:
  #   build: ./video-consumer
  #   restart: on-failure
  #   depends_on:
  #     - kafka
  #   volumes:
  #     - ./video-consumer:/app
  #     - ./output/video:/output
  
  display:
    build: ./display
    restart: on-failure
    depends_on:
      - kafka
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ./display:/app


  word-consumer:
    build: ./word-consumer
    restart: on-failure
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    volumes:
      - ./output:/output
      - ./word-consumer:/app
      - ./output:/app/output

  audio-consumer:
    build: ./audio-consumer
    restart: on-failure
    depends_on:
      - kafka
    volumes:
      - ./audio-consumer:/app
      - ./output/audio:/output
      
  diagram-consumer:
    build: ./diagram-consumer
    restart: on-failure
    depends_on:
      - kafka
    volumes:
      - ./diagram-consumer:/app
      - ./output/diagram:/output

  ocr-consumer:
    build: ./ocr-consumer
    restart: on-failure
    depends_on:
      - kafka
    volumes:
      - ./ocr-consumer:/app
      - ./output/text:/output

  

volumes:
  kafka_data:
