version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"   # Internal Docker network (used by other containers)
      - "9094:9094"   # External host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper
    restart: unless-stopped

  kafka-setup:
    build: ./kafka
    depends_on:
      - kafka
    command: ["/bin/bash", "-c", "/kafka-setup.sh"]
    volumes:
      - ./kafka/kafka-setup.sh:/kafka-setup.sh
    restart: "no"

  producer:
    build: ./producer
    restart: on-failure
    depends_on:
      - kafka
    volumes:
      - ./input:/input
      - ./producer:/app

  display:
    build: ./display
    restart: on-failure
    depends_on:
      - kafka
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ./display:/app

  word-consumer:
    build: ./word-consumer
    restart: on-failure
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    volumes:
      - ./output:/output
      - ./word-consumer:/app
      - ./output:/app/output

  audio-consumer:
    build: ./audio-consumer
    restart: on-failure
    depends_on:
      - kafka
    volumes:
      - ./audio-consumer:/app
      - ./output/audio:/output

  ocr-consumer:
    build: ./ocr-consumer
    restart: on-failure
    depends_on:
      - kafka
    volumes:
      - ./ocr-consumer:/app
      - ./output/text:/output

volumes:
  kafka_data:
